version: '3.4'

services:
  satoshitestapp:
    image: satoshitestapp:1.0
    build:
      context: .
      dockerfile: SatoshiTestApp/Dockerfile

  satoshitestapi:
    image: satoshitestapi:1.0
    build:
      context: .
      dockerfile: SathoshiTestApi/Dockerfile

  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "phlo@123"
      ACCEPT_EULA: "Y"